name: kinject
description: "Simple Dependency Injector based on InheritedWidget to provide singleton and factory instances easily"
version: 1.0.3
homepage: https://github.com/Kanza-OSS/kinject
repository: https://github.com/Kanza-OSS/kinject
issue_tracker: https://github.com/Kanza-OSS/kinject/issues
documentation: https://github.com/Kanza-OSS/kinject
topics: [dependency-injection, inherited-widget]
# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  kanza_lints: ^1.0.0
